export const GET_STRATEGIES_REQUEST = '@@hedera/GET_STRATEGIES_REQUEST';
export const GET_STRATEGIES_SUCCESS = '@@hedera/GET_STRATEGIES_SUCCESS';
export const GET_STRATEGIES_FAILURE = '@@hedera/GET_STRATEGIES_FAILURE';

export const GET_CASE_REQUEST = '@@hedera/GET_CASE_REQUEST';
export const GET_CASE_SUCCESS = '@@hedera/GET_CASE_SUCCESS';
export const GET_CASE_FAILURE = '@@hedera/GET_CASE_FAILURE';

export const UPDATE_CASE_REQUEST = '@@hedera/UPDATE_CASE_REQUEST';
export const UPDATE_CASE_SUCCESS = '@@hedera/UPDATE_CASE_SUCCESS';
export const UPDATE_CASE_FAILURE = '@@hedera/UPDATE_CASE_FAILURE';

